spark.master local[*]
spark.app.name spark-lakehouse

spark.ui.port 4040
spark.port.maxRetries 50

spark.driver.bindAddress 0.0.0.0
spark.driver.host localhost

spark.sql.shuffle.partitions 8
spark.default.parallelism 8

spark.sql.catalogImplementation in-memory
spark.sql.legacy.createHiveTableByDefault false

spark.sql.warehouse.dir /lake

spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog

spark.sql.catalog.local org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.local.type hadoop
spark.sql.catalog.local.warehouse /lake
